module  -- shake: keep-all --deprecated_module: ignore

public import Paucity.Counting.ApPos
public import Paucity.Counting.ChiIff
public import Paucity.Counting.CountTnDiv
public import Paucity.Counting.HSumLt
public import Paucity.Counting.HnLower
public import Paucity.Counting.LSubset
public import Paucity.Counting.MobiusHn
public import Paucity.Counting.Nonusable
public import Paucity.Counting.SIdentity
public import Paucity.Counting.TwoP
public import Paucity.Defs.Ad
public import Paucity.Defs.Bd
public import Paucity.Defs.Boxnorm
public import Paucity.Defs.Degenerate
public import Paucity.Defs.Dn
public import Paucity.Defs.E
public import Paucity.Defs.Fd
public import Paucity.Defs.Fourier
public import Paucity.Defs.H
public import Paucity.Defs.Hd
public import Paucity.Defs.Hn
public import Paucity.Defs.Ind
public import Paucity.Defs.Lambda
public import Paucity.Defs.LambdaKL
public import Paucity.Defs.Lambdamin
public import Paucity.Defs.Lat
public import Paucity.Defs.Lattice
public import Paucity.Defs.LatticeBox
public import Paucity.Defs.Ln
public import Paucity.Defs.M
public import Paucity.Defs.Maj
public import Paucity.Defs.Nd
public import Paucity.Defs.Notation.E
public import Paucity.Defs.Notation.Res
public import Paucity.Defs.Notation.Units
public import Paucity.Defs.Q
public import Paucity.Defs.Resonant
public import Paucity.Defs.S
public import Paucity.Defs.Tn
public import Paucity.Defs.Usable
public import Paucity.Defs.Wd
public import Paucity.Defs.Weight
public import Paucity.Estimates.DivisorBound
public import Paucity.Estimates.FourierBound
public import Paucity.Estimates.FourierZero
public import Paucity.Estimates.GeomSum
public import Paucity.Estimates.Hyperbola
public import Paucity.Estimates.NOverPhi
public import Paucity.Estimates.QLower
public import Paucity.Estimates.QSmall
public import Paucity.Estimates.SinLower
public import Paucity.Estimates.TauFactorLarge
public import Paucity.Estimates.TauFactorSmall
public import Paucity.Estimates.TauGeTwoOmega
public import Paucity.Estimates.TotientLower
public import Paucity.Estimates.WeightSum
public import Paucity.External.Lnz
public import Paucity.Lattice.AxisBound
public import Paucity.Lattice.BdSwap
public import Paucity.Lattice.FamilyCount
public import Paucity.Lattice.FamilyCover
public import Paucity.Lattice.FiniteIndexLattice
public import Paucity.Lattice.LatticeAlt
public import Paucity.Lattice.MinAttained
public import Paucity.Lattice.MinPrimitive
public import Paucity.Lattice.OneVanishing
public import Paucity.Lattice.PrimitiveBasis
public import Paucity.Lattice.Quadcount
public import Paucity.Lattice.Reduction
public import Paucity.Main.CountDegen
public import Paucity.Main.CountResonant
public import Paucity.Main.CountSmallM
public import Paucity.Main.LatticeTriangles
public import Paucity.Majorant.DetLambda
public import Paucity.Majorant.DivDecomp
public import Paucity.Majorant.EBound
public import Paucity.Majorant.Majd
public import Paucity.Majorant.NdFourier
public import Paucity.Majorant.Orthogonality
public import Paucity.Majorant.PhiMobius
